---
- name: Check if certificate exists or has been changed
  import_tasks: test-cert-exists.yml

- name: Stop services to allow certbot to generate a cert.
  service:
    name: "{{ item }}"
    state: stopped
  when: not letsencrypt_cert_exists.stat.exists
  with_items: "{{ certbot_create_standalone_stop_services }}"

- name: Generate new certificate if one doesn't exist.
  shell: "{{ certbot_create_command }}"
  when: not letsencrypt_cert_exists.stat.exists

- name: Persist domain list to host
  copy:
    content: "{{ cert_item.domains }}"
    dest: /etc/letsencrypt/domains-{{ cert_item.domains | first }}
  when: letsencrypt_cert_updated.rc != 0

- name: Start services after cert has been generated.
  service:
    name: "{{ item }}"
    state: started
  when: not letsencrypt_cert_exists.stat.exists
  with_items: "{{ certbot_create_standalone_stop_services }}"
